name: check-bookmarklet-size.yml
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  check-bookmarklet-size:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
      - run: npm install terser
      - run: node scripts/check-bookmarklet-sizes.js
