name: sh-format-automatic.yml
on:
  repository_dispatch:
    types:
      - format-sh-code

jobs:
  sh-format-automatic:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.client_payload.ref }}
      - name: Install shfmt
        run: sudo snap install shfmt
      - run: shfmt -w .
      - run: |
          if ! git diff --quiet; then
            branch_name=format-sh-code-in-${BASE#refs/heads/}-branch-at-$(date -u +"%Y-%m-%dT%H-%M-%S")
            git config --global user.name 'github-actions[bot]'
            git config --global user.email 'github-actions[bot]@users.noreply.github.com'
            git checkout -b $branch_name
            git commit -a -m "Format sh code in ${BASE#refs/heads/} branch"
            git push --set-upstream origin $branch_name
            pr_url=$(gh pr create -B ${BASE#refs/heads/} -f)
            pr_number=${pr_url##*/}
            gh pr merge $pr_number --auto --squash
            gh workflow run check-format-pr-status.yml -f pr_number=$pr_number -f branch_name=$branch_name
          fi
        env:
          BASE: ${{ github.event.client_payload.ref || 'main' }}
          GH_TOKEN: ${{ secrets.PAT }}
