name: shell-test.yml
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  shell-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install shfmt
        run: sudo snap install shfmt
      - run: shfmt -d .
        id: format-check
        continue-on-error: true
      - uses: peter-evans/repository-dispatch@v3
        if: steps.format-check.outcome == 'failure'
        with:
          token: ${{ secrets.PAT }}
          repository: ${{ github.repository }}
          event-type: format-sh-code
          client-payload: '{"ref": "${{ github.head_ref || github.ref_name }}"}'
      - run: shfmt -d .
        if: steps.format-check.outcome == 'failure'
      - run: shfmt -f . | xargs -r shellcheck
